name: Build and Release

on:
  push:
    branches: [ main ]
    tags:
      - 'v*'
  pull_request:
    branches: [ main ]

permissions:
  contents: write

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Configure CMake
      run: |
        mkdir build
        cd build
        cmake ..
    
    - name: Build
      run: |
        cd build
        cmake --build . --config Release
    
    - name: Create Package
      run: |
        cd build
        cpack -G NSIS -C Release
        cpack -G ZIP -C Release
    
    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: windows-packages
        path: |
          build/*.exe
          build/*.zip
    
    - name: Upload Release Asset
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: |
          build/*.exe
          build/*.zip

  build-macos:
    runs-on: macos-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Configure CMake
      run: |
        mkdir build
        cd build
        cmake -DCMAKE_BUILD_TYPE=Release ..
    
    - name: Build
      run: |
        cd build
        make
    
    - name: Create Package
      run: |
        cd build
        cpack -G DragNDrop
        cpack -G ZIP
    
    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: macos-packages
        path: |
          build/*.dmg
          build/*.zip
    
    - name: Upload Release Asset
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: |
          build/*.dmg
          build/*.zip

  build-linux:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake
    
    - name: Configure CMake
      run: |
        mkdir build
        cd build
        cmake -DCMAKE_BUILD_TYPE=Release ..
    
    - name: Build
      run: |
        cd build
        make
    
    - name: Create Package
      run: |
        cd build
        cpack -G DEB
        cpack -G TGZ
    
    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: linux-packages
        path: |
          build/*.deb
          build/*.tar.gz
    
    - name: Upload Release Asset
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: |
          build/*.deb
          build/*.tar.gz